name: mobile_app
description: "Cross-platform Flutter boilerplate with KindeAuth, RBAC, and offline-ready architecture."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State + Routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1

  # Networking + Offline
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Security + Auth
  flutter_secure_storage: ^9.2.2
  flutter_appauth: ^6.0.0
  jwt_decode: ^0.3.1

  # Config + Utilities
  flutter_dotenv: ^5.2.1
  intl: ^0.20.1
  uuid: ^4.5.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0

  # UI
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10
  gap: ^3.0.1

  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

  # Assets
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/.env

flutter_native_splash:
  color: "#0B1020"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#0B1020"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 23
